# vim:set ft=dockerfile:
FROM mdillon/postgis:latest 
MAINTAINER ...

# Custom initialization scripts
COPY ./scripts/create_user.sh   /docker-entrypoint-initdb.d/10-create_user.sh
COPY ./scripts/create_db.sh     /docker-entrypoint-initdb.d/20-create_db.sh
RUN mv /docker-entrypoint-initdb.d/postgis.sh /docker-entrypoint-initdb.d/09-postgis.sh
